package com.dalish.wx.miniapp.entity;

import java.util.Date;

public class Activity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.id
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.title
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.link_url
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String linkUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.category
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_date
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_date
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.start_time
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.end_time
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.created_at
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.updated_at
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity.detail
     *
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    private String detail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.id
     *
     * @return the value of activity.id
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.id
     *
     * @param id the value for activity.id
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.title
     *
     * @return the value of activity.title
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.title
     *
     * @param title the value for activity.title
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.link_url
     *
     * @return the value of activity.link_url
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getLinkUrl() {
        return linkUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.link_url
     *
     * @param linkUrl the value for activity.link_url
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setLinkUrl(String linkUrl) {
        this.linkUrl = linkUrl == null ? null : linkUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.category
     *
     * @return the value of activity.category
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.category
     *
     * @param category the value for activity.category
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_date
     *
     * @return the value of activity.start_date
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_date
     *
     * @param startDate the value for activity.start_date
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_date
     *
     * @return the value of activity.end_date
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_date
     *
     * @param endDate the value for activity.end_date
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.start_time
     *
     * @return the value of activity.start_time
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.start_time
     *
     * @param startTime the value for activity.start_time
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime == null ? null : startTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.end_time
     *
     * @return the value of activity.end_time
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.end_time
     *
     * @param endTime the value for activity.end_time
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime == null ? null : endTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.created_at
     *
     * @return the value of activity.created_at
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.created_at
     *
     * @param createdAt the value for activity.created_at
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.updated_at
     *
     * @return the value of activity.updated_at
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.updated_at
     *
     * @param updatedAt the value for activity.updated_at
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity.detail
     *
     * @return the value of activity.detail
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity.detail
     *
     * @param detail the value for activity.detail
     * @mbg.generated Wed Nov 18 16:40:11 CST 2020
     */
    public void setDetail(String detail) {
        this.detail = detail == null ? null : detail.trim();
    }
}
